name: hp
dependencies:
- openssl=1.0.2d=0
- pip
- pip:
  - "ipython[notebook]<4"
  - toolz
  - snakeviz
  - pygraphviz
  #- pyth
- python=3.5
- spacy
- pandas
- numexpr
- gensim
- seaborn
- joblib
- networkx




